---
title: "randomForest model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{randomForest}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(dplyr)
library(tidypredict)
library(randomForest)
```

```{r}
library(tidypredict)
library(randomForest)

set.seed(100)

model <- randomForest(Species ~ .,data = iris ,ntree = 100, proximity = TRUE)

model
```

## `tidypredict_to_column()`

```{r}
iris %>%
  tidypredict_to_column(model) %>%
  head(10)
```

## How it works

`tidypredict` bases the parser on the ouput from the the `tree::getTree()` function
```{r}
getTree(model, labelVar = TRUE) %>% 
  as.tibble() 
```

The parsed model has one entry per path 
```{r}
parse_model(model)
```

The Tidy Eval formula is one `dplyr::case_when()` statement
```{r}
tidypredict_fit(model)
```

Here an example of how the formula will be translated into SQL
```{r}
tidypredict_sql(model, dbplyr::simulate_dbi())
```

## How it performs

Currently, the formula matches 147 out of 150 prediction for Iris
```{r}
test <- tidypredict_test(model, iris, threshold = 5)

test

test$raw_results %>%
  filter(predict != tidypredict)
```